description = 'Connecting vehicle enthusiasts around the world. Sign up to get notified when it’s ready.'
mailchimp_url = 'https://app.us6.list-manage.com/subscribe/post?u=df777ccb3a44077e29f0a3339&amp;id=ddc60eebb8'
